### ISSUE TITLE
[CHECKLIST]: NEW REPOSITORY SETTINGS

### ISSUE THREAD

**Issue by RChloe** [tektronix/TekDrive-LabVIEW-SDK#1]
### Have you added any of the following to your repo yet?

- [ ] -[README that follows guidelines](https://github.com/tektronix/best-practice-resources/blob/main/README-templates)
- [X] -[LICENSE](https://github.com/tektronix/best-practice-resources/blob/main/README.md#license)
- [X] -[Global Codeowner](https://github.com/tektronix/best-practice-resources/blob/main/.github/folder-guide.md#codeowners)
- [X] -[Branch Protection](https://github.com/tektronix/best-practice-resources/blob/main/README.md#branch-protection)
- [X] -[dependabot](https://github.com/tektronix/best-practice-resources/blob/main/.github/folder-guide.md#dependabot)
- [X] -[Repo Lint Action](https://github.com/tektronix/best-practice-resources/blob/main/.github/folder-guide.md#repo-lint)
- [X] -[CodeScan](https://github.com/tektronix/best-practice-resources/blob/main/.github/folder-guide.md#codescan)
- [X] -[About description with topics](https://github.com/tektronix/best-practice-resources/blob/main/README.md#topics)
